# Generated by Django 2.0.7 on 2018-07-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('gen', models.TextField()),
                ('sp', models.TextField()),
                ('ssp', models.TextField()),
                ('en', models.TextField()),
                ('rec', models.TextField()),
                ('cnt', models.TextField()),
                ('loc', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('type', models.TextField()),
                ('file', models.TextField()),
                ('lic', models.TextField()),
                ('url', models.TextField()),
                ('q', models.TextField()),
                ('time', models.TextField()),
                ('date', models.TextField()),
                ('sonogram_url', models.TextField()),
                ('elevation_m', models.IntegerField()),
                ('length_s', models.FloatField()),
                ('sampling_rate_hz', models.IntegerField()),
                ('bitrate_bps', models.IntegerField()),
                ('channels', models.IntegerField()),
                ('volume', models.TextField()),
                ('speed', models.TextField()),
                ('pitch', models.TextField()),
                ('sound_length', models.TextField()),
                ('number_of_notes', models.TextField()),
                ('variable', models.TextField()),
            ],
        ),
    ]
