# Generated by Django 2.0.7 on 2018-07-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenocanto', '0004_auto_20180722_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
