# Generated by Django 2.0.7 on 2018-07-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenocanto', '0005_auto_20180722_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesaltname',
            name='alt_name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='speciesaltname',
            unique_together={('alt_name', 'species')},
        ),
    ]
