include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # See https://dart-lang.github.io/linter/lints/ for a list of all available lints.
    # Those enabled by `pendantic` do not need to be listed here.
    avoid_print: true # For production logs, use a `Logger` from the `logging` package.
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_future: true # Probably a sign of a bug.
    avoid_returning_null_for_void: true
    avoid_setters_without_getters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true # The caller might wish to `await` it.
    await_only_futures: true # It makes no sense to await something that's not a `Future`.
    cancel_subscriptions: true
    cascade_invocations: true # Not sure about this one yet, let's try it for a while.
    close_sinks: true
    directives_ordering: true
    empty_statements: true
    exhaustive_cases: true
    file_names: true
    hash_and_equals: true
    implementation_imports: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    non_constant_identifier_names: true
    only_throw_errors: true
    overridden_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_not_operator: true
    prefer_mixin: false # `ChangeNotifier` is a class and it's not in our code.
    prefer_null_aware_operators: true
    provide_deprecation_message: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    test_types_in_equals: true
    unnecessary_brace_in_string_interps: false # Sometimes nice to use them for consistency: '${a}_${b}'
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    use_is_even_rather_than_modulo: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    void_checks: true